### ISSUE TITLE
Incompatible with 1.16.5

### ISSUE THREAD

**Issue by NighthowlerStudios** [plex1on/Infection#3] opened 2022-09-26 11:24 UTC

**Comment by katelyynn** [comment] 2022-09-26 14:59
hmm yeah, the datapack doesn't seem to be working as intended on 1.16. do you have any reason to still be on 1.16?

**Comment by katelyynn** [comment] 2022-09-26 15:40
should be fixed in the next release! (2022.0926)

**Closed as completed** 2022-09-26 15:44 UTC
Labels: bug

**Comment by NighthowlerStudios** [comment] 2022-09-26 22:48
> hmm yeah, the datapack doesn't seem to be working as intended on 1.16. do you have any reason to still be on 1.16?

I wanted to use the pack alongside my gun mod as testing for its functionality.  Plans sorta fell flat but I might try again at some point.

**Comment by katelyynn** [comment] 2022-09-27 07:54
oh, well the datapack should work as intended in 1.16 now
